# Generated by Django 5.0.7 on 2025-03-26 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myChatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chathistory',
            old_name='session',
            new_name='session_id',
        ),
    ]
